apiVersion: apps/v1
kind: Deployment
metadata:
 name: backend-app
 labels:
   app: back-deployment
spec:
 selector:
   matchLabels:
     app: express-app
 template:
   metadata:
     labels:
       app: express-app
   spec:
     containers:
     - name: express-container
       image: rahmafrioui/express-app:latest
       resources:
         limits:
           memory: "128Mi"
           cpu: "500m"
       ports:
       - containerPort: 3000
