apiVersion: v1
kind: Service
metadata:
 name: react-service
 labels:
   run: react-app-service
spec:
 type: NodePort
 ports:
 - port: 8081
   targetPort: 80
   protocol: TCP
   name: http
 selector:
   app: react-app
